require(here)
rope= read.csv(here("data", "rope.csv"))

rm(list = ls())

rope = read.csv(here("data", "rope.csv"))
rope$rope.type = factor(rope$rope.type)
levels(rope$rope.type)
       
n_obs = nrow(rope)
n_obs
n_groups = length(levels(rope$rope.type))
n_groups
                        
ss_tot = 
df_tot = ....
                        
agg_sq_resids = ....
ss_within = ....
df_within = ....
                        
ss_among = ....
df_among = ....
                        
ms_within = ....
ms_among  = ....
                        
f_ratio = ....
f_pval = ....